# This is a basic workflow to help you get started with Actions

name: Create_Issues

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  [create]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: ddradar/choose-random-action@v1
        id: pick_diff
        with:
          contents: |
            352
            554
            724
            767
            865
            867

      - uses: ddradar/choose-random-action@v1
        id: pick_easy1
        with:
          contents: |
            257
            354
            397
            485

      - uses: ddradar/choose-random-action@v1
        id: pick_easy2
        with:
          contents: |
            687
            889
            932
            979
      
      - name: Create Issue From File (Diff)
        uses: peter-evans/create-issue-from-file@v2.3.2
        with:
          title: Ticket nr. ${{ steps.pick_diff.outputs.selected }}
          content-filepath: ./.issues/issue${{ steps.pick_diff.outputs.selected }}.md

      - name: Create Issue From File (Easy1)
        uses: peter-evans/create-issue-from-file@v2.3.2
        with:
          title: Ticket nr. ${{ steps.pick_easy1.outputs.selected }}
          content-filepath: ./.issues/issue${{ steps.pick_easy1.outputs.selected }}.md

      - name: Create Issue From File (Easy2)
        uses: peter-evans/create-issue-from-file@v2.3.2
        with:
          title: Ticket nr. ${{ steps.pick_easy2.outputs.selected }}
          content-filepath: ./.issues/issue${{ steps.pick_easy2.outputs.selected }}.md
