# This is a basic workflow to help you get started with Actions

name: Create_Issues

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  [create]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - uses: ddradar/choose-random-action@v1
        id: pick
        with:
          contents: |
            foo
            bar
            baz
      
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2.3.2
        with:
          title: Nieuw ticket ${{ steps.pick.outputs.selected }}
          content-filepath: ./README.md
          
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v2.3.2
        with:
          title: Nieuw ticket
          content-filepath: ./issue.md
